# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Utilities for representing attribute domains.

A categorical attribute can be characterized by a finite set of possible
values. A numerical attribute can be characterized by a range of possible
values. A free-form text attribute represents unstructured text fields that
may be generated by a language model. In typical differential privacy
scenarios, it is assumed/required that the domain is known in advance. This
module provides dataclasses for representing this information.

In this library we provide special treatment for out-of-domain values.  There
are two ways that we support handling out-of-domain values: (1) directly model
them or (2) map them to an element of the domain.

Values from categorical attributes that are not in the list of possible values
are mapped to some value in the list (default is the first element).
For safety, it's best practice to add a `None` value as the first entry in the
list of possible values for categorical attributes if you are unsure if there
are out-of-domain values.  If you know there are not any out-of-domain values,
then you can (and should) ignore this advice, so that downstream mechanisms
don't generate out-of-domain values when none should exist.

Similarly, values from numerical attributes that are outside of the range
[min_value, max_value] (or not even a numerical type) are clipped to this range
if `clip_to_range=True`. Otherewise, they are mapped to a special out-of-domain
value.  As before we recommend setting clip_to_range=False to directly model
out-of-domain values.  If you are sure none should exist, you can (and should)
ignore this advice, so that downstream mechanisms don't generate out-of-domain
values when none should exist.
"""

from collections.abc import Mapping
import functools
import math
import pathlib

from typing import Any, Literal, TypeAlias

import attr
import pandas as pd
import yaml

PathType = pathlib.Path

CategoricalValue: TypeAlias = None | bool | int | str | pd.Interval

IntervalHandling = Literal['midpoint', 'sample', 'interval']


@attr.define(frozen=True)
class CategoricalAttribute:
  """Dataclass for storing metadata about a categorical attribute.

  If the set of possible values is known in advance, this should be be
  specified via the `possible_values` attribute. If a value does not exist
  in this list, it will be mapped to possible_values[out_of_domain_index].
  If your data does not contain out-of-domain values, this will be a no-op.
  If you are unsure, we recommend you include a `None` or other special
  value as the first entry of the `possible_values` list.

  If the set of possible is not known in advance, use the
  OpenSetCategoricalAttribute class instead.

  Attributes:
    possible_values: A list of possible values for this attribute.
    out_of_domain_index: The index into possible_values that out-of-domain
      values should be mapped to.
    description: An optional semantic description of the attribute.
  """

  possible_values: list[CategoricalValue] = attr.field(converter=list)
  out_of_domain_index: int = attr.field(default=0)
  description: str | None = attr.field(default=None)

  def __attrs_post_init__(self):
    if self.size == 0:
      raise ValueError('Possible values must not be empty.')
    if self.out_of_domain_index < 0 or self.out_of_domain_index >= self.size:
      raise ValueError(
          f'out_of_domain_index must be in [0, {self.size-1}], got'
          f' {self.out_of_domain_index}.'
      )

  @functools.cached_property
  def size(self) -> int:
    """Returns the number of possible values."""
    return len(self.possible_values)

  def standardize(self, value: Any) -> CategoricalValue:
    """Standardizes a value to one of the possible values."""
    if value in self.possible_values:
      return value
    return self.possible_values[self.out_of_domain_index]


@attr.define(frozen=True)
class OpenSetCategoricalAttribute:
  """Dataclass representing a categorical attribute with unknown domain.

  Given an attribute with an unknown domain, we will attempt to automatically
  infer the set of possible values from the data in a DP manner. Values that
  do not appear frequently enough will be mapped to a default value.

  Attributes:
    default_value: The default value for out-of-domain entries.
    description: An optional semantic description of the attribute.
  """

  default_value: CategoricalValue | None = None
  description: str | None = None


@attr.define(frozen=True)
class NumericalAttribute:
  """Dataclass for storing metadata about a numerical attribute.

  We require knowing the range of possible values in advance, and these must be
  specified via the `min_value` and `max_value` attributes. If
  `out_of_domain_allowed` is True, out-of-domain values will be mapped to
  `None`. If it is False, out-of-domain values will be clipped to
  (min_value, max_value) if they are a numeric type, and to min_value otherwise.

  Attributes:
    min_value: The minimum possible value for this attribute (inclusive).
    max_value: The maximum possible value for this attribute (inclusive).
    clip_to_range: Specifies how out-of-domain values should be treated. If
      True, out-of-domain values will be clipped to the range [min_value,
      max_value] if they are a numeric type, and to min_value otherwise.  If
      False, out-of-domain values will be grouped together and treated as a
      single special out-of-domain value.
    dtype: The dtype of the data (either 'int' or 'float').
    interval_handling: Controls how discretized intervals are converted back to
      numerical values. 'midpoint' returns the interval midpoint (or the finite
      endpoint if the other is infinite). 'sample' draws uniformly from the
      interval (or returns the finite endpoint if the other is infinite).
      'interval' keeps the pd.Interval in the output unchanged.
    description: An optional semantic description of the attribute.
  """

  min_value: float = attr.field(converter=float)
  max_value: float = attr.field(converter=float)
  clip_to_range: bool = attr.field(default=True)
  dtype: str = attr.field(default='float')
  interval_handling: str = attr.field(default='midpoint')
  description: str | None = attr.field(default=None)

  @min_value.validator  # pytype: disable=attribute-error
  def _validate_min_max(self, *_):
    if self.min_value > self.max_value:
      raise ValueError(
          f'min_value ({self.min_value}) must be less than or equal to'
          f' max_value ({self.max_value})'
      )

  @dtype.validator  # pytype: disable=attribute-error
  def _validate_dtype(self, *_):
    if self.dtype not in ['int', 'float']:
      raise ValueError(
          f'dtype must be either "int" or "float", got {self.dtype}.'
      )

  @interval_handling.validator  # pytype: disable=attribute-error
  def _validate_interval_handling(self, *_):
    if self.interval_handling not in ['midpoint', 'sample', 'interval']:
      raise ValueError(
          'interval_handling must be "midpoint", "sample", or "interval",'
          f' got {self.interval_handling}.'
      )

  @property
  def exclusive_min_value(self) -> float:
    """Returns the exclusive minimum value for this attribute."""
    if self.dtype == 'int':
      return self.min_value - 1
    return math.nextafter(self.min_value, -math.inf)

  def standardize(self, value: Any) -> int | float | None:
    """Standardizes a value to one of the possible values."""
    if self.clip_to_range:
      low_value = invalid_value = self.min_value
      high_value = self.max_value
    else:
      low_value = high_value = invalid_value = None
    try:
      value = float(value)  # works for anything that converts to float.
      if math.isnan(value):
        return invalid_value
      elif value < self.min_value:
        return low_value
      elif value > self.max_value:
        return high_value
      elif self.dtype == 'int':
        return round(value)
      return value
    except (ValueError, TypeError):
      return invalid_value


@attr.define(frozen=True)
class FreeFormTextAttribute:
  """Dataclass for storing metadata about a free-form text attribute.

  Represents an unstructured text field whose values may be generated by a
  language model.  Generated text will be truncated to `max_tokens` tokens.

  Attributes:
    max_tokens: Maximum number of tokens for this text field. Generated outputs
      will be truncated to this length.
    description: An optional semantic description of the attribute.
    formatting: Optional formatting requirements (e.g., structural constraints
      the text must conform to).
    exemplar: An optional example value for this attribute.
  """

  max_tokens: int = attr.field(default=256)
  description: str | None = attr.field(default=None)
  formatting: str | None = attr.field(default=None)
  exemplar: str | None = attr.field(default=None)


AttributeType = (
    CategoricalAttribute
    | NumericalAttribute
    | OpenSetCategoricalAttribute
    | FreeFormTextAttribute
)


def to_yaml_file(domain: Mapping[str, AttributeType], filepath: str | PathType):
  """Writes a dictionary of Attribute objects to a YAML file."""
  yaml_data = {}
  for name, attr_obj in domain.items():
    yaml_data[name] = attr.asdict(attr_obj)
  with open(filepath, 'w') as f:
    yaml.dump(yaml_data, f, default_flow_style=False)


def from_yaml_file(filepath: str | PathType) -> Mapping[str, AttributeType]:
  """Reads a dictionary of Attribute objects from a YAML file."""
  with open(filepath, 'r') as f:
    yaml_data = yaml.safe_load(f)
  domain = {}
  for name, attr_data in yaml_data.items():
    if 'possible_values' in attr_data:
      domain[name] = CategoricalAttribute(**attr_data)
    elif 'min_value' in attr_data:
      domain[name] = NumericalAttribute(**attr_data)
    elif 'max_tokens' in attr_data:
      domain[name] = FreeFormTextAttribute(**attr_data)
    elif not attr_data:
      domain[name] = OpenSetCategoricalAttribute()
    else:
      raise ValueError(f'Invalid YAML data for attribute: {name}')
  return domain
